Project 1 - Wiki/wiki_django/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search_entry, name="search_entry"),
    path("add", views.add, name="add"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random", views.random_entry, name="random")
]

Project 1 - Wiki/wiki_django/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project 1 - Wiki/wiki_django/encyclopedia/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import random
import markdown2

from . import util

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="Content", widget=forms.Textarea)

class EditEntryForm(forms.Form):
    content = forms.CharField(label="Content", widget=forms.Textarea)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    content = markdown2.markdown(util.get_entry(title))
    if content == None:
        return render(request, "encyclopedia/error_404.html")
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": content
        })

def search_entry(request):
    query = request.GET.get('q', '')

    if query in util.list_entries():
        return HttpResponseRedirect(reverse("wiki:entry", kwargs={'title': query}))

    else:
        list_result = [entry for entry in util.list_entries() if query in entry]
        return render(request, "encyclopedia/search_entry.html", {
            "search": query,
            "entries": list_result
        })

def add(request):
    if request.method == 'POST':
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if title not in util.list_entries():
                content = form.cleaned_data["content"]
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("wiki:entry", kwargs={'title': title}))
            else:
                return render(request, "encyclopedia/add.html", {
                    "form": form,
                    "error": True
                })

        else:
            return render(request, "encyclopedia/add.html", {
                "form": form,
                "error" : False
            })
    else:
        return render(request, "encyclopedia/add.html", {
            "form": NewEntryForm(),
            "error" : False
        })

def edit(request, title):
    if request.method == 'POST':
        form = EditEntryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:entry", kwargs={'title': title}))

        else:
            return render(request, "encyclopedia/edit.html", {
                "title": title,
                "form": form
            })

    else:
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": EditEntryForm({"content":content})
        })

def random_entry(request):
    title = random.choice(util.list_entries())
    return HttpResponseRedirect(reverse("wiki:entry", kwargs={'title': title})) 

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia - Add
{%endblock %}

{% block body %}
<h1>Create a page</h1>

{% if error %}
<p>This page already exist</p>
{% endif %}

<form action="{% url 'wiki:add' %}" method="post">
    {% csrf_token %} {{ form }}
    <input type="submit" />
</form>
{% endblock %}

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia - Add
{%endblock %}

{% block body %}
<h1>Edit the page - {{ title }}</h1>

<form action="{% url 'wiki:edit' title=title %}" method="post">
    {% csrf_token %} {{ form }}
    <input type="submit" />
</form>
{% endblock %}

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia - {{ title }}
{%endblock %}

{% block body %}
<a href="{% url 'wiki:edit' title=title %}">Edit this page</a>
{{ content|safe }}
{% endblock %}

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
404
{%endblock %}

{% block body %}
<h1>404</h1>
The requested page was not found
{% endblock %}

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/error_404.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
404
{%endblock %}

{% block body %}
<h1>Error 404</h1>
The page that you try to find doesn't exist
{% endblock %}

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{%endblock %}
{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li>
        <a href="{% url 'wiki:entry' title=entry %}"> {{ entry }} </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form action="{% url 'wiki:search_entry' %}" method="get">
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'wiki:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'wiki:add' %}">Create New Page</a>
            </div>
            <div>
                <a href="{% url 'wiki:random' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</body>

</html>

Project 1 - Wiki/wiki_django/encyclopedia/templates/encyclopedia/search_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia - Search
{%endblock %}

{% block body %}
<h1> Search: {{ search }} </h1>
<ul>
    {% for entry in entries %}
    <li>
        <a href="{% url 'wiki:entry' title=entry %}"> {{ entry }} </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}